name: io2
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anyio=4.7.0=py312h06a4308_0
  - aom=3.6.0=h6a678d5_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=21.2.0=py312h5eee18b_1
  - asttokens=3.0.0=py312h06a4308_0
  - async-lru=2.0.4=py312h06a4308_0
  - babel=2.16.0=py312h06a4308_0
  - beautifulsoup4=4.13.4=py312h06a4308_0
  - blas=1.0=mkl
  - bleach=6.2.0=py312h06a4308_0
  - bottleneck=1.4.2=py312ha883a20_0
  - brotli-python=1.0.9=py312h6a678d5_9
  - brotlicffi=1.0.9.2=py312h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.19.1=h5eee18b_0
  - ca-certificates=2025.9.9=h06a4308_0
  - cairo=1.16.0=he5ede1b_6
  - certifi=2025.8.3=py312h06a4308_0
  - cffi=1.17.1=py312h1fdaa30_1
  - chardet=5.2.0=py312h06a4308_0
  - click=8.2.1=py312h06a4308_0
  - comm=0.2.1=py312h06a4308_0
  - contourpy=1.3.1=py312hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.11=py312h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.1=h6a678d5_0
  - fontconfig=2.14.1=h55d465d_3
  - fonttools=4.55.3=py312h5eee18b_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - graphite2=1.3.14=h295c915_1
  - h11=0.16.0=py312h06a4308_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - httpcore=1.0.9=py312h06a4308_0
  - httpx=0.28.1=py312h06a4308_0
  - icu=73.1=h6a678d5_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - ipykernel=6.29.5=py312h06a4308_1
  - ipython=9.1.0=py312h06a4308_0
  - ipython_pygments_lexers=1.1.1=py312h06a4308_0
  - ipywidgets=8.1.5=py312h06a4308_0
  - jedi=0.19.2=py312h06a4308_0
  - jinja2=3.1.6=py312h06a4308_0
  - joblib=1.5.2=py312h06a4308_0
  - jpeg=9e=h5eee18b_3
  - json5=0.9.25=py312h06a4308_0
  - jsonschema=4.25.0=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter=1.1.1=py312h06a4308_0
  - jupyter-lsp=2.2.5=py312h06a4308_0
  - jupyter_client=8.6.3=py312h06a4308_0
  - jupyter_console=6.6.3=py312h06a4308_1
  - jupyter_core=5.8.1=py312h06a4308_0
  - jupyter_events=0.12.0=py312h06a4308_0
  - jupyter_server=2.16.0=py312h06a4308_0
  - jupyter_server_terminals=0.5.3=py312h06a4308_0
  - jupyterlab=4.4.4=py312h06a4308_0
  - jupyterlab_pygments=0.3.0=py312h06a4308_0
  - jupyterlab_server=2.27.3=py312h06a4308_0
  - jupyterlab_widgets=3.0.15=py312h06a4308_0
  - kiwisolver=1.4.8=py312h6a678d5_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.40=h12ee557_0
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libavif=1.1.1=h5eee18b_0
  - libcups=2.4.2=h252cb56_2
  - libcurl=8.14.1=hc1efc7f_1
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.2=h37c7471_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libkrb5=1.21.3=h520c7b4_3
  - libllvm15=15.0.7=he89c38a_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.4=h02b6914_2
  - libprotobuf=5.29.3=h3cdef7c_1
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - llvmlite=0.44.0=py312hc1e8f15_1
  - lmdb=0.9.29=h2531618_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py312h5eee18b_0
  - matplotlib=3.10.0=py312h06a4308_0
  - matplotlib-base=3.10.0=py312hbfdbfaf_0
  - matplotlib-inline=0.1.6=py312h06a4308_0
  - mesalib=25.1.5=h31e3550_0
  - mistune=3.1.2=py312h06a4308_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_2
  - mkl_fft=1.3.11=py312h5eee18b_0
  - mkl_random=1.2.8=py312h526ad5a_0
  - mysql=8.4.0=h721767e_2
  - nbclient=0.10.2=py312h06a4308_0
  - nbconvert=7.16.6=py312h06a4308_0
  - nbconvert-core=7.16.6=py312h06a4308_0
  - nbconvert-pandoc=7.16.6=py312h06a4308_0
  - nbformat=5.10.4=py312h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py312h06a4308_0
  - nltk=3.9.1=py312h06a4308_0
  - notebook=7.4.4=py312h06a4308_0
  - notebook-shim=0.2.4=py312h06a4308_0
  - numba=0.61.2=py312h6a678d5_0
  - numexpr=2.11.0=py312hf4471f9_0
  - numpy-base=2.0.0=py312h0da6c21_1
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.4=h42fbc30_0
  - openssl=3.0.18=hd6dcaed_0
  - overrides=7.4.0=py312h06a4308_0
  - packaging=25.0=py312h06a4308_0
  - pandoc=2.12=h06a4308_3
  - pandocfilters=1.5.0=pyhd3eb1b0_0
  - parso=0.8.4=py312h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pexpect=4.9.0=py312h06a4308_0
  - pillow=11.3.0=py312hb1c3d2d_0
  - pip=25.1=pyhc872135_2
  - pixman=0.40.0=h7f8727e_1
  - prometheus_client=0.21.1=py312h06a4308_0
  - prompt-toolkit=3.0.43=py312h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyparsing=3.2.0=py312h06a4308_0
  - pyqt=6.7.1=py312h8dad735_2
  - pyqt6-sip=13.9.1=py312h6ce4db3_2
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.9=h5148396_0
  - python-dateutil=2.9.0post0=py312h06a4308_2
  - python-fastjsonschema=2.20.0=py312h06a4308_0
  - python-json-logger=3.2.1=py312h06a4308_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - pytz=2025.2=py312h06a4308_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - pyzmq=26.2.0=py312h6a678d5_0
  - qtbase=6.7.3=h10a5587_4
  - qtconsole=5.6.1=py312h06a4308_1
  - qtdeclarative=6.7.3=h7934f7d_1
  - qtpy=2.4.1=py312h06a4308_0
  - qtsvg=6.7.3=he4bddd1_1
  - qttools=6.7.3=h5a8de97_1
  - qtwebchannel=6.7.3=h7934f7d_1
  - qtwebsockets=6.7.3=h7934f7d_1
  - readline=8.3=hc2a1206_0
  - referencing=0.30.2=py312h06a4308_0
  - requests=2.32.4=py312h06a4308_0
  - rfc3339-validator=0.1.4=py312h06a4308_0
  - rfc3986-validator=0.1.1=py312h06a4308_0
  - rpds-py=0.22.3=py312h4aa5aa6_0
  - scipy=1.16.0=py312h0cc6016_0
  - seaborn=0.13.2=py312h06a4308_3
  - send2trash=1.8.2=py312h06a4308_1
  - setuptools=78.1.1=py312h06a4308_0
  - sip=6.10.0=py312h6a678d5_0
  - six=1.17.0=py312h06a4308_0
  - sniffio=1.3.0=py312h06a4308_0
  - soupsieve=2.5=py312h06a4308_0
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - terminado=0.17.1=py312h06a4308_0
  - tinycss2=1.4.0=py312h06a4308_0
  - tk=8.6.14=h993c535_1
  - tornado=6.5.1=py312h5eee18b_0
  - tqdm=4.67.1=py312he106c6f_0
  - traitlets=5.14.3=py312h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=15.1.0=py312h5eee18b_1
  - urllib3=2.5.0=py312h06a4308_0
  - wcwidth=0.2.13=py312h06a4308_0
  - webencodings=0.5.1=py312h06a4308_2
  - websocket-client=1.8.0=py312h06a4308_0
  - wheel=0.45.1=py312h06a4308_0
  - widgetsnbextension=4.0.13=py312h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - zstd=1.5.6=hc292b87_0
  - pip:
      - accelerate==1.10.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - attrs==25.3.0
      - beartype==0.14.1
      - better-abc==0.0.3
      - bm25s==0.2.14
      - charset-normalizer==3.4.3
      - circuitsvis==1.43.3
      - datasets==4.0.0
      - dill==0.3.8
      - einops==0.8.1
      - fancy-einsum==0.0.3
      - filelock==3.18.0
      - frozenlist==1.7.0
      - fsspec==2025.3.0
      - git-filter-repo==2.47.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - hf-xet==1.1.7
      - huggingface-hub==0.34.4
      - idna==3.10
      - importlib-metadata==8.7.0
      - jaxtyping==0.3.2
      - markdown-it-py==4.0.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.6.4
      - multiprocess==0.70.16
      - networkx==3.5
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.8.90
      - pandas==2.3.1
      - platformdirs==4.3.8
      - propcache==0.3.2
      - protobuf==6.31.1
      - psutil==7.0.0
      - pyarrow==21.0.0
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - regex==2025.7.34
      - rich==14.1.0
      - safetensors==0.6.2
      - sentencepiece==0.2.0
      - sentry-sdk==2.34.1
      - smmap==5.0.2
      - sympy==1.14.0
      - tokenizers==0.21.4
      - torch==2.8.0
      - transformer-lens==0.0.0
      - transformers==4.55.0
      - transformers-stream-generator==0.0.5
      - triton==3.4.0
      - typeguard==4.4.4
      - typing-extensions==4.15.0
      - typing-inspection==0.4.1
      - wadler-lindig==0.1.7
      - wandb==0.21.1
      - wikiextractor==3.0.6
      - xxhash==3.5.0
      - yarl==1.20.1
      - zipp==3.23.0
